"""empty message

Revision ID: 3b2897c5f9a8
Revises: 
Create Date: 2023-06-09 14:39:44.202305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2897c5f9a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    task_table=op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(task_table,
    [
        {'title':'Play',
         'description':'play',
         'due_date':'1686291661',
         'status':'InComplete'},
        {
        "title":"work",
        "description":"work",
        "due_date":"1686291663",
        "status":"InComplete"}
    ])



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
